/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubjectId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const QnAEntry = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : UserId,
  'question' : IDL.Text,
  'createdAt' : Timestamp,
  'answer' : IDL.Text,
  'subjectId' : SubjectId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EventId = IDL.Nat;
export const VotingEventView = IDL.Record({
  'id' : EventId,
  'winnerSubject' : IDL.Opt(IDL.Text),
  'proposedSubjects' : IDL.Vec(IDL.Text),
  'createdAt' : Timestamp,
  'voteCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'isLocked' : IDL.Bool,
  'hasVoted' : IDL.Bool,
});
export const QuizId = IDL.Nat;
export const QuestionId = IDL.Nat;
export const QuizOption = IDL.Record({
  'text' : IDL.Text,
  'isCorrect' : IDL.Bool,
});
export const QuizQuestion = IDL.Record({
  'id' : QuestionId,
  'questionText' : IDL.Text,
  'options' : IDL.Vec(QuizOption),
});
export const QuizView = IDL.Record({
  'id' : QuizId,
  'createdAt' : Timestamp,
  'subjectId' : SubjectId,
  'questions' : IDL.Vec(QuizQuestion),
});
export const SubjectView = IDL.Record({
  'id' : SubjectId,
  'title' : IDL.Text,
  'endDate' : Timestamp,
  'description' : IDL.Text,
  'startDate' : Timestamp,
});
export const StudentView = IDL.Record({
  'id' : UserId,
  'displayName' : IDL.Text,
  'rank' : IDL.Nat,
  'roleLabel' : IDL.Text,
  'totalPoints' : IDL.Nat,
});
export const QuizAttempt = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : UserId,
  'answers' : IDL.Vec(IDL.Nat),
  'score' : IDL.Nat,
  'isPerfect' : IDL.Bool,
  'attemptedAt' : Timestamp,
  'quizId' : QuizId,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'askQuestion' : IDL.Func([SubjectId, IDL.Text], [QnAEntry], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'castVote' : IDL.Func([EventId, IDL.Text], [], []),
  'clearMyGeminiApiKey' : IDL.Func([], [], []),
  'createVotingEvent' : IDL.Func([IDL.Vec(IDL.Text)], [VotingEventView], []),
  'generateQuiz' : IDL.Func([SubjectId], [QuizView], []),
  'getActiveSubject' : IDL.Func([], [IDL.Opt(SubjectView)], ['query']),
  'getActiveVotingEvent' : IDL.Func([], [IDL.Opt(VotingEventView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(StudentView)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(StudentView)], ['query']),
  'getMyQnA' : IDL.Func([SubjectId], [IDL.Vec(QnAEntry)], ['query']),
  'getMyQuizAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
  'getMyRank' : IDL.Func([], [IDL.Nat], ['query']),
  'getQuiz' : IDL.Func([SubjectId], [IDL.Opt(QuizView)], ['query']),
  'getRoleInfo' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'displayName' : IDL.Text,
          'isAdmin' : IDL.Bool,
          'isOwner' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getStudentProfile' : IDL.Func([UserId], [IDL.Opt(StudentView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMyGeminiConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'lockVoting' : IDL.Func([EventId], [IDL.Opt(IDL.Text)], []),
  'registerStudent' : IDL.Func([IDL.Text], [StudentView], []),
  'registerWithPassword' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : StudentView, 'err' : IDL.Text })],
      [],
    ),
  'setActiveSubject' : IDL.Func(
      [IDL.Text, Timestamp, Timestamp],
      [SubjectView],
      [],
    ),
  'setMyGeminiApiKey' : IDL.Func([IDL.Text], [], []),
  'submitQuizAttempt' : IDL.Func([QuizId, IDL.Vec(IDL.Nat)], [QuizAttempt], []),
  'updateMyDisplayName' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubjectId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const QnAEntry = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : UserId,
    'question' : IDL.Text,
    'createdAt' : Timestamp,
    'answer' : IDL.Text,
    'subjectId' : SubjectId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EventId = IDL.Nat;
  const VotingEventView = IDL.Record({
    'id' : EventId,
    'winnerSubject' : IDL.Opt(IDL.Text),
    'proposedSubjects' : IDL.Vec(IDL.Text),
    'createdAt' : Timestamp,
    'voteCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'isLocked' : IDL.Bool,
    'hasVoted' : IDL.Bool,
  });
  const QuizId = IDL.Nat;
  const QuestionId = IDL.Nat;
  const QuizOption = IDL.Record({ 'text' : IDL.Text, 'isCorrect' : IDL.Bool });
  const QuizQuestion = IDL.Record({
    'id' : QuestionId,
    'questionText' : IDL.Text,
    'options' : IDL.Vec(QuizOption),
  });
  const QuizView = IDL.Record({
    'id' : QuizId,
    'createdAt' : Timestamp,
    'subjectId' : SubjectId,
    'questions' : IDL.Vec(QuizQuestion),
  });
  const SubjectView = IDL.Record({
    'id' : SubjectId,
    'title' : IDL.Text,
    'endDate' : Timestamp,
    'description' : IDL.Text,
    'startDate' : Timestamp,
  });
  const StudentView = IDL.Record({
    'id' : UserId,
    'displayName' : IDL.Text,
    'rank' : IDL.Nat,
    'roleLabel' : IDL.Text,
    'totalPoints' : IDL.Nat,
  });
  const QuizAttempt = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : UserId,
    'answers' : IDL.Vec(IDL.Nat),
    'score' : IDL.Nat,
    'isPerfect' : IDL.Bool,
    'attemptedAt' : Timestamp,
    'quizId' : QuizId,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'askQuestion' : IDL.Func([SubjectId, IDL.Text], [QnAEntry], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'castVote' : IDL.Func([EventId, IDL.Text], [], []),
    'clearMyGeminiApiKey' : IDL.Func([], [], []),
    'createVotingEvent' : IDL.Func([IDL.Vec(IDL.Text)], [VotingEventView], []),
    'generateQuiz' : IDL.Func([SubjectId], [QuizView], []),
    'getActiveSubject' : IDL.Func([], [IDL.Opt(SubjectView)], ['query']),
    'getActiveVotingEvent' : IDL.Func(
        [],
        [IDL.Opt(VotingEventView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(StudentView)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(StudentView)], ['query']),
    'getMyQnA' : IDL.Func([SubjectId], [IDL.Vec(QnAEntry)], ['query']),
    'getMyQuizAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
    'getMyRank' : IDL.Func([], [IDL.Nat], ['query']),
    'getQuiz' : IDL.Func([SubjectId], [IDL.Opt(QuizView)], ['query']),
    'getRoleInfo' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'displayName' : IDL.Text,
            'isAdmin' : IDL.Bool,
            'isOwner' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getStudentProfile' : IDL.Func([UserId], [IDL.Opt(StudentView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMyGeminiConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'lockVoting' : IDL.Func([EventId], [IDL.Opt(IDL.Text)], []),
    'registerStudent' : IDL.Func([IDL.Text], [StudentView], []),
    'registerWithPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : StudentView, 'err' : IDL.Text })],
        [],
      ),
    'setActiveSubject' : IDL.Func(
        [IDL.Text, Timestamp, Timestamp],
        [SubjectView],
        [],
      ),
    'setMyGeminiApiKey' : IDL.Func([IDL.Text], [], []),
    'submitQuizAttempt' : IDL.Func(
        [QuizId, IDL.Vec(IDL.Nat)],
        [QuizAttempt],
        [],
      ),
    'updateMyDisplayName' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };