/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EventId = bigint;
export interface QnAEntry {
  'id' : bigint,
  'studentId' : UserId,
  'question' : string,
  'createdAt' : Timestamp,
  'answer' : string,
  'subjectId' : SubjectId,
}
export type QuestionId = bigint;
export interface QuizAttempt {
  'id' : bigint,
  'studentId' : UserId,
  'answers' : Array<bigint>,
  'score' : bigint,
  'isPerfect' : boolean,
  'attemptedAt' : Timestamp,
  'quizId' : QuizId,
}
export type QuizId = bigint;
export interface QuizOption { 'text' : string, 'isCorrect' : boolean }
export interface QuizQuestion {
  'id' : QuestionId,
  'questionText' : string,
  'options' : Array<QuizOption>,
}
export interface QuizView {
  'id' : QuizId,
  'createdAt' : Timestamp,
  'subjectId' : SubjectId,
  'questions' : Array<QuizQuestion>,
}
export interface StudentView {
  'id' : UserId,
  'displayName' : string,
  'rank' : bigint,
  'roleLabel' : string,
  'totalPoints' : bigint,
}
export type SubjectId = bigint;
export interface SubjectView {
  'id' : SubjectId,
  'title' : string,
  'endDate' : Timestamp,
  'description' : string,
  'startDate' : Timestamp,
}
export type Timestamp = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VotingEventView {
  'id' : EventId,
  'winnerSubject' : [] | [string],
  'proposedSubjects' : Array<string>,
  'createdAt' : Timestamp,
  'voteCounts' : Array<[string, bigint]>,
  'isLocked' : boolean,
  'hasVoted' : boolean,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'askQuestion' : ActorMethod<[SubjectId, string], QnAEntry>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'castVote' : ActorMethod<[EventId, string], undefined>,
  'clearMyGeminiApiKey' : ActorMethod<[], undefined>,
  'createVotingEvent' : ActorMethod<[Array<string>], VotingEventView>,
  'generateQuiz' : ActorMethod<[SubjectId], QuizView>,
  'getActiveSubject' : ActorMethod<[], [] | [SubjectView]>,
  'getActiveVotingEvent' : ActorMethod<[], [] | [VotingEventView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<StudentView>>,
  'getMyProfile' : ActorMethod<[], [] | [StudentView]>,
  'getMyQnA' : ActorMethod<[SubjectId], Array<QnAEntry>>,
  'getMyQuizAttempts' : ActorMethod<[], Array<QuizAttempt>>,
  'getMyRank' : ActorMethod<[], bigint>,
  'getQuiz' : ActorMethod<[SubjectId], [] | [QuizView]>,
  'getRoleInfo' : ActorMethod<
    [Principal],
    { 'displayName' : string, 'isAdmin' : boolean, 'isOwner' : boolean }
  >,
  'getStudentProfile' : ActorMethod<[UserId], [] | [StudentView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isMyGeminiConfigured' : ActorMethod<[], boolean>,
  'lockVoting' : ActorMethod<[EventId], [] | [string]>,
  'registerStudent' : ActorMethod<[string], StudentView>,
  'registerWithPassword' : ActorMethod<
    [string, string],
    { 'ok' : StudentView } |
      { 'err' : string }
  >,
  'setActiveSubject' : ActorMethod<[string, Timestamp, Timestamp], SubjectView>,
  'setMyGeminiApiKey' : ActorMethod<[string], undefined>,
  'submitQuizAttempt' : ActorMethod<[QuizId, Array<bigint>], QuizAttempt>,
  'updateMyDisplayName' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];