/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VotingEventView {
    id: EventId;
    winnerSubject?: string;
    proposedSubjects: Array<string>;
    createdAt: Timestamp;
    voteCounts: Array<[string, bigint]>;
    isLocked: boolean;
    hasVoted: boolean;
}
export type Timestamp = bigint;
export interface StudentView {
    id: UserId;
    displayName: string;
    rank: bigint;
    roleLabel: string;
    totalPoints: bigint;
}
export type EventId = bigint;
export interface QuizQuestion {
    id: QuestionId;
    questionText: string;
    options: Array<QuizOption>;
}
export type QuestionId = bigint;
export interface QuizView {
    id: QuizId;
    createdAt: Timestamp;
    subjectId: SubjectId;
    questions: Array<QuizQuestion>;
}
export type UserId = Principal;
export interface SubjectView {
    id: SubjectId;
    title: string;
    endDate: Timestamp;
    description: string;
    startDate: Timestamp;
}
export interface QuizAttempt {
    id: bigint;
    studentId: UserId;
    answers: Array<bigint>;
    score: bigint;
    isPerfect: boolean;
    attemptedAt: Timestamp;
    quizId: QuizId;
}
export interface QnAEntry {
    id: bigint;
    studentId: UserId;
    question: string;
    createdAt: Timestamp;
    answer: string;
    subjectId: SubjectId;
}
export interface QuizOption {
    text: string;
    isCorrect: boolean;
}
export type SubjectId = bigint;
export type QuizId = bigint;
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    askQuestion(subjectId: SubjectId, question: string): Promise<QnAEntry>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    castVote(eventId: EventId, subject: string): Promise<void>;
    clearMyGeminiApiKey(): Promise<void>;
    createVotingEvent(proposedSubjects: Array<string>): Promise<VotingEventView>;
    generateQuiz(subjectId: SubjectId): Promise<QuizView>;
    getActiveSubject(): Promise<SubjectView | null>;
    getActiveVotingEvent(): Promise<VotingEventView | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLeaderboard(): Promise<Array<StudentView>>;
    getMyProfile(): Promise<StudentView | null>;
    getMyQnA(subjectId: SubjectId): Promise<Array<QnAEntry>>;
    getMyQuizAttempts(): Promise<Array<QuizAttempt>>;
    getMyRank(): Promise<bigint>;
    getQuiz(subjectId: SubjectId): Promise<QuizView | null>;
    getRoleInfo(id: Principal): Promise<{
        displayName: string;
        isAdmin: boolean;
        isOwner: boolean;
    }>;
    getStudentProfile(id: UserId): Promise<StudentView | null>;
    isCallerAdmin(): Promise<boolean>;
    isMyGeminiConfigured(): Promise<boolean>;
    lockVoting(eventId: EventId): Promise<string | null>;
    registerStudent(displayName: string): Promise<StudentView>;
    registerWithPassword(displayName: string, password: string): Promise<{
        __kind__: "ok";
        ok: StudentView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setActiveSubject(title: string, startDate: Timestamp, endDate: Timestamp): Promise<SubjectView>;
    setMyGeminiApiKey(key: string): Promise<void>;
    submitQuizAttempt(quizId: QuizId, answers: Array<bigint>): Promise<QuizAttempt>;
    updateMyDisplayName(name: string): Promise<void>;
}
import type { EventId as _EventId, QuizView as _QuizView, StudentView as _StudentView, SubjectView as _SubjectView, Timestamp as _Timestamp, UserRole as _UserRole, VotingEventView as _VotingEventView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async askQuestion(arg0: SubjectId, arg1: string): Promise<QnAEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.askQuestion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askQuestion(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async castVote(arg0: EventId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.castVote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.castVote(arg0, arg1);
            return result;
        }
    }
    async clearMyGeminiApiKey(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearMyGeminiApiKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearMyGeminiApiKey();
            return result;
        }
    }
    async createVotingEvent(arg0: Array<string>): Promise<VotingEventView> {
        if (this.processError) {
            try {
                const result = await this.actor.createVotingEvent(arg0);
                return from_candid_VotingEventView_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVotingEvent(arg0);
            return from_candid_VotingEventView_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateQuiz(arg0: SubjectId): Promise<QuizView> {
        if (this.processError) {
            try {
                const result = await this.actor.generateQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateQuiz(arg0);
            return result;
        }
    }
    async getActiveSubject(): Promise<SubjectView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSubject();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSubject();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveVotingEvent(): Promise<VotingEventView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveVotingEvent();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveVotingEvent();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<StudentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getMyProfile(): Promise<StudentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyQnA(arg0: SubjectId): Promise<Array<QnAEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQnA(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQnA(arg0);
            return result;
        }
    }
    async getMyQuizAttempts(): Promise<Array<QuizAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQuizAttempts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQuizAttempts();
            return result;
        }
    }
    async getMyRank(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRank();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRank();
            return result;
        }
    }
    async getQuiz(arg0: SubjectId): Promise<QuizView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuiz(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuiz(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoleInfo(arg0: Principal): Promise<{
        displayName: string;
        isAdmin: boolean;
        isOwner: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoleInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoleInfo(arg0);
            return result;
        }
    }
    async getStudentProfile(arg0: UserId): Promise<StudentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isMyGeminiConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isMyGeminiConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isMyGeminiConfigured();
            return result;
        }
    }
    async lockVoting(arg0: EventId): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.lockVoting(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lockVoting(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerStudent(arg0: string): Promise<StudentView> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(arg0);
            return result;
        }
    }
    async registerWithPassword(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: StudentView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWithPassword(arg0, arg1);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWithPassword(arg0, arg1);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async setActiveSubject(arg0: string, arg1: Timestamp, arg2: Timestamp): Promise<SubjectView> {
        if (this.processError) {
            try {
                const result = await this.actor.setActiveSubject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setActiveSubject(arg0, arg1, arg2);
            return result;
        }
    }
    async setMyGeminiApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMyGeminiApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMyGeminiApiKey(arg0);
            return result;
        }
    }
    async submitQuizAttempt(arg0: QuizId, arg1: Array<bigint>): Promise<QuizAttempt> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAttempt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAttempt(arg0, arg1);
            return result;
        }
    }
    async updateMyDisplayName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyDisplayName(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_VotingEventView_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VotingEventView): VotingEventView {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentView]): StudentView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizView]): QuizView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubjectView]): SubjectView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VotingEventView]): VotingEventView | null {
    return value.length === 0 ? null : from_candid_VotingEventView_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EventId;
    winnerSubject: [] | [string];
    proposedSubjects: Array<string>;
    createdAt: _Timestamp;
    voteCounts: Array<[string, bigint]>;
    isLocked: boolean;
    hasVoted: boolean;
}): {
    id: EventId;
    winnerSubject?: string;
    proposedSubjects: Array<string>;
    createdAt: Timestamp;
    voteCounts: Array<[string, bigint]>;
    isLocked: boolean;
    hasVoted: boolean;
} {
    return {
        id: value.id,
        winnerSubject: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.winnerSubject)),
        proposedSubjects: value.proposedSubjects,
        createdAt: value.createdAt,
        voteCounts: value.voteCounts,
        isLocked: value.isLocked,
        hasVoted: value.hasVoted
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _StudentView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: StudentView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
